### PR TITLE
Run deploy with sudo

### PR DESCRIPTION
**Pull request by timurvafin**

### CODE REVIEW

**Comment by maxprokopiev** [comment]
Just thought about it
May be we don't need `bin/deploy` at all? we can run `/home/#{project}/application/script/deploy` in (sh ...) call

**Comment by timurvafin** [comment]
Correct, will send pull request

On Tuesday, April 16, 2013, Max Prokopiev wrote:

> Just thought about it
> May be we don't need bin/deploy at all? we can run
> /home/#{project}/application/script/deploy in (sh ...) call
> 
> —
> Reply to this email directly or view it on GitHubhttps://github.com/fs/services-clojure/pull/5#issuecomment-16448086
> .

## 

Timur Vafin

**Comment by timurvafin** [comment]
@juggler checkout https://github.com/fs/services-clojure/commit/4e0a3d520f97cd9a904ef4af8ee91d3d87acf010

**Comment by timurvafin** [comment]
@juggler ping

**Comment by maxprokopiev** [comment]
I think, we also need to check for existence of directory, I'll check this later :)

**Pull request closed without merging**
